/**
 * Writes src/generated/operations.ts from the SDK's openapi.json through
 * operationsFromDocument (the same function the docs build uses). Committed,
 * so the CLI typechecks on a fresh checkout; `pnpm generate` refreshes it
 * after the SDK regenerates, and CI does the same on every merge to main.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { operationsFromDocument, type OpenApiDocument } from '../src/operations-from-spec';

const specPath = fileURLToPath(new URL('../../sdk/openapi.json', import.meta.url));
const outDir = fileURLToPath(new URL('../src/generated', import.meta.url));
const outPath = fileURLToPath(new URL('../src/generated/operations.ts', import.meta.url));

const doc = JSON.parse(readFileSync(specPath, 'utf8')) as OpenApiDocument;
const operations = operationsFromDocument(doc);

const header = `// Generated by scripts/generate-operations.ts from ../../sdk/openapi.json. Do not edit.
import type { CliOperation } from '../operations-types';

export const OPERATIONS: readonly CliOperation[] = `;
mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, `${header}${JSON.stringify(operations, null, 2)};\n`);
console.log(`Wrote ${outPath} (${operations.length} operations)`);
